# Generated by Django 5.0 on 2023-12-16 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackmes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crackme',
            name='level',
        ),
        migrations.AddField(
            model_name='crackme',
            name='binary_file',
            field=models.FileField(null=True, upload_to='crackme_binaries/'),
        ),
        migrations.AddField(
            model_name='crackme',
            name='hardness_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('crackme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crackmes.crackme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('binary_file', models.FileField(null=True, upload_to='solution_binaries/')),
                ('crackme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crackmes.crackme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
