# Generated by Django 5.0 on 2023-12-16 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackmes', '0004_alter_crackme_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crackme',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='crackme',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_title'),
        ),
    ]
