# Generated by Django 5.0.1 on 2024-01-29 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 30, 2, 4, 12, 943444))),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Author', models.CharField(max_length=20)),
                ('Language', models.CharField(max_length=20)),
                ('Arch', models.CharField(max_length=20)),
                ('Difficulty', models.IntegerField()),
                ('Quality', models.IntegerField()),
                ('Platform', models.CharField(max_length=20)),
                ('fileName', models.CharField(max_length=255)),
                ('fileContent', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 30, 2, 4, 12, 943444))),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('fileName', models.CharField(max_length=255)),
                ('fileContent', models.TextField()),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 30, 2, 4, 12, 943444))),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 30, 2, 4, 12, 943444))),
            ],
        ),
    ]
