# Generated by Django 5.0.1 on 2024-01-31 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 9, 44, 47, 573943)),
        ),
        migrations.AlterField(
            model_name='rank',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 9, 44, 47, 573943)),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 9, 44, 47, 573943)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 9, 44, 47, 573943)),
        ),
    ]
