# Generated by Django 5.0 on 2023-12-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('NameLink', models.CharField(max_length=120)),
                ('Author', models.CharField(max_length=20)),
                ('AuthorLink', models.CharField(max_length=120)),
                ('Language', models.CharField(max_length=20)),
                ('Arch', models.CharField(max_length=20)),
                ('Difficulty', models.IntegerField()),
                ('Quality', models.IntegerField()),
                ('Platform', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Solution', models.IntegerField()),
                ('Comments', models.IntegerField()),
            ],
        ),
    ]
