# Generated by Django 5.0.1 on 2024-02-01 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_comments_created_at_alter_rank_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderUserId', models.IntegerField()),
                ('getterUserId', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 2, 1, 18, 59, 36, 8897))),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 18, 59, 36, 8897)),
        ),
        migrations.AlterField(
            model_name='rank',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 18, 59, 36, 8897)),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 18, 59, 36, 8897)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 18, 59, 36, 8897)),
        ),
    ]
